base:
  mass: 0.8               # Base mass in Kg
  x_size: 0.195           # Dimension in x axis
  y_size: 0.08            # Dimension in y axis
  z_size: 0.005           # Dimension in z axis
  diameter: 0.09
  height: 0.10
  mesh: 'chassis.stl'  # Name of the mesh files. Leave it empty ('') to have a white base.
